public with sharing class ContactListController {
    	private String sortOrder = 'LastName';
    // 	public List<Contact> getContacts(){
    //         String query = 'SELECT Id, FirstName, LastName, Title, Email ' +
    //         'FROM Contact ' +
    //         'ORDER BY ' + sortOrder + ' ASC ' +
    //         'LIMIT 10';
    //         String v1 = query;
    //         List<Contact> results = Database.query(v1);
    //         return results;

    // }
}